stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - echo "Building Spring Boot application..."
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

unit-test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - echo "Running unit tests..."
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

deploy-job:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  needs:
    - job: unit-test-job
    - job: build-job
      artifacts: true
  script:
    - echo "Starting deployment to Azure..."
    - echo "$AZURE_PUBLISH_PROFILE" > publishProfile.xml
    - ARTIFACT=$(ls target/*.jar | head -n 1)
    - az account set --subscription "$AZURE_SUBSCRIPTION_ID"
    - az login --service-principal --username $AZURE_CLIENT_ID --password "$AZURE_FULL_SECRET" --tenant $AZURE_TENANT_ID
    - echo "Azure login successful."
    - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEB_APP_NAME --src-path "$ARTIFACT" --type jar  
    - echo "Application deployed succefully!"
  environment:
    name: production